### ISSUE TITLE
HW PDF Graphs

### ISSUE THREAD

**Issue by 1826949** [vincentkslim/cs285_homework_fall2020#1]
Hi Vincent,

Just wondering how you did the graphs for the solution pdf's. When I ran the experiments all I got out were numbers on my terminal.

Thanks!

**Comment by vincentkslim** [comment]
Hello,

The values that you need (train return, eval return, env steps, etc.) are both printed to the terminal and logged to a tensorboard log file. The tensorboard log files are usually located in the data folder inside each individual homework directory (e.g. hw1/data), and it creates a new folder and logfile for each run that you do on your local machine. Tensorboard has a nice interface that you can use to view the data in a web browser by navigating to the data directory in a terminal and using `tensorboard --logdir .`. To read from the logfiles, look at the `dataviz.ipynb` file in each homework directory in my repository, near the top you should see an example of how to read data logged to the tensorboard log file. For example:

```
def get_section_results(file):
    """
        requires tensorflow==1.12.0
    """
    X = []
    Y = []
    for e in tf.compat.v1.train.summary_iterator(file):
        for v in e.summary.value:
            if v.tag == 'Train_EnvstepsSoFar':
                X.append(v.simple_value)
            elif v.tag == 'Eval_AverageReturn':
                Y.append(v.simple_value)
    return X, Y
```
Also, ignore the `requires tensorflow==1.12.0`, the example code was updated to work on tensorflow 2.0. Afterward, you can process the data using `pandas` and `seaborn` (which is what I did), or whichever data analysis package of your choice.

Hope this helps. 

Vincent

**Comment by 1826949** [comment]
Thank you so much Vincent, this really helped!
