### ISSUE TITLE
[Discuss] maybe an error in hw3 solution.pdf

### ISSUE THREAD

**Issue by Kin-Zhang** [vincentkslim/cs285_homework_fall2020#3]
![image](https://user-images.githubusercontent.com/35365764/121016857-3538ba80-c7cf-11eb-9bed-bdf060c6cf21.png)

The things I want to mention is for this command there is no n_layers
```bash
python run_hw3_dqn.py --env_name LunarLander-v3 --exp_name q3_hparam1
```

Here is the reason:
Firstly, we search for params `n_layers` and we will find out in agent/ac_agent.py and critics/bootstrapped_continuous_critic.py and policies/MLP_policy.py

Secondly, we can find out only `run_hw3_actor_critic.py` will use ac_agent and MLP_policy, for `run_hw3_dqn.py` is only DQN_agent with DQNCritic and ArgMaxPolicy which don't have `n_layers` params in it.

Now, let's back to the command:
```bash
python run_hw3_dqn.py --env_name LunarLander-v3 --exp_name q3_hparam1
```
it's only dqn.py.

If there is any problem or something I misunderstand pls let me know, happy to discuss with you.

**Comment by vincentkslim** [comment]
Oh, for this I simply changed the utility function that created the Q network, you can see it [here](https://github.com/vincentkslim/cs285_homework_fall2020/blob/8c8b6e34c22d828ff3d6e736db025b2ed5917617/hw3/cs285/infrastructure/dqn_utils.py#L83). I know it isn't that pretty, but you can see that I just commented out/modified lines as necessary to add layers or change the hidden layer size. It's not great but it works :).

**Comment by Kin-Zhang** [comment]
Oh I see, thanks for replying
